version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
    depends_on:
    - backend
  backend:
    build:
      context: ./backend