version: '3'
services:
  frontend:
    image: ghcr.io/alex123a/fortune-cookie-frontend:${COMMIT_HASH}
    ports:
      - "8080:8080"
    environment:
      - BACKEND_DNS=backend
    depends_on:
    - backend
  backend:
    image: ghcr.io/alex123a/fortune-cookie-backend:${COMMIT_HASH}