apiVersion: v1
kind: Service
metadata:
  labels:
    run: fortune-cookie-backend
  name: fortune-cookie-backend
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    run: fortune-cookie-backend
  type: ClusterIP
