apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-cookie-backend
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      run: fortune-cookie-backend
  template:
    metadata:
      labels:
        run: fortune-cookie-backend
    spec:
      containers:
        - name: fortune-cookie-backend
          image: ghcr.io/alex123a/fortune-cookie-backend:latest
          imagePullPolicy: Always
          resources: {}
          env:
            - name: REDIS_DNS
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_DNS
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
            
