apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-cookie-backend
spec:
  selector:
    matchLabels:
      run: fortune-cookie-backend
  template:
    metadata:
      labels:
        run: fortune-cookie-backend
    spec:
      containers:
      - name: fortune-cookie-backend
        image: ghcr.io/alex123a/fortune-cookie-backend:latest
        imagePullPolicy: Always
        resources: {}
        env:
          - name: REDIS_DNS
            value: redis-server
          - name: REDIS_PORT
            value: "6379"
