apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cookie-pvc
spec:
  # storageClassName: "cookie-storage-class"
  storageClassName: "gp2"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi