apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-cookie-frontend
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: fortune-cookie-frontend
  template:
    metadata:
      labels:
        app: fortune-cookie-frontend
    spec:
      containers:
      - name: fortune-cookie-frontend
        image: ghcr.io/alex123a/fortune-cookie-frontend:latest
        imagePullPolicy: Always
        resources: {}
        env:
          - name: BACKEND_DNS
            value: fortune-cookie-backend
          - name: BACKEND_PORT
            value: "9000"