apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      run: redis-server
  template:
    metadata:
      labels:
        run: redis-server
    spec:
      volumes:
        - name: cookie-pvc
          persistentVolumeClaim: 
            claimName: cookie-pvc
      containers:
        - name: redis-server
          image: "redis:latest"
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
            - name: cookie-pvc
              mountPath: /var/lib/redis/data
              subPath: cookie-pvc
            