apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis-server
  name: redis-server
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    run: redis-server
  type: ClusterIP
