apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  selector:
    matchLabels:
      run: redis-server
  template:
    metadata:
      labels:
        run: redis-server
    spec:
      containers:
      - name: redis-server
        image: "redis:latest"
        imagePullPolicy: Always
        resources: {}