name: testing-the-waters
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: clone-down
        uses: actions/checkout@v3
      - name: install-go
        uses: actions/setup-go@v4
      - name: build-backend
        run: cd backend/ && go build
      - name: build-frontend
        run: cd frontend/ && go build
      - name: cd frontend/ && test-frontend
        run: go test
