name: run_kubernetes
on:
  workflow_run:
    workflows: ["testing-the-waters"]
    types:
      - completed
    branches: [master]
jobs:
  Run-kubernetes:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Apply kubernetes
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig && kubectl --kubeconfig kubeconfig apply -f ./kubernetes
