name: run_kubernetes
on:
  workflow_run:
    workflows: ["testing-the-waters"]
    types:
      - completed
    branches: [master]
env:
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Run-kubernetes:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Apply kubernetes
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig && kubectl --kubeconfig kubeconfig apply -f ./kubernetes && kubectl --kubeconfig kubeconfig set image deployment/fortune-cookie-frontend fortune-cookie-frontend=ghcr.io/alex123a/fortune-cookie-frontend:1.0-${{ github.sha }} && kubectl --kubeconfig kubeconfig set image deployment/fortune-cookie-backend fortune-cookie-backend=ghcr.io/alex123a/fortune-cookie-backend:1.0-${{ github.sha }} && kubectl --kubeconfig kubeconfig rollout status deployment fortune-cookie-frontend && kubectl --kubeconfig kubeconfig rollout status deployment fortune-cookie-backend

