name: run_kubernetes
on:
  workflow_run:
    workflows: ["testing-the-waters"]
    types:
      - completed
    branches: [master]
jobs:
  Run-kubernetes:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Apply kubernetes
        run: echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig && kubectl --kubeconfig kubeconfig apply -f ./kubernetes && kubectl --kubeconfig kubeconfig rollout status deployment fortune-cookie-frontend && kubectl --kubeconfig kubeconfig rollout status deployment fortune-cookie-backend

